### ISSUE TITLE
Cannot Jailbreak (iOS 14.8 & iOS 14.6)

### ISSUE THREAD

**Issue by Tech4HelpYT** [Aditya20110/downr1n-gui#12]
Whenever I try to jailbreak on any version without taurine (pongo) it says it cannot find dualra1n ipa.

How do I fix this?

Please respond.

**Comment by Aditya20110** [comment]
Hi,

**Comment by Aditya20110** [comment]
Wait i fix it

**Comment by Tech4HelpYT** [comment]
I also tried with adding the dualra1n.app folder frrom the dualr1n repo.

**Comment by Tech4HelpYT** [comment]
> Wait i fix it

Ok thank you!

**Comment by Aditya20110** [comment]
It wouldn’t work

**Comment by Tech4HelpYT** [comment]
> It wouldn’t work

Why?

**Comment by Tech4HelpYT** [comment]
> Kinda unaware about this issue idk why it happened i did updated dependencies

I also tried with original downr1n and had no issues until the jailbreak (with same error), but this one didn't work the downgrade because it got stuck at cp: -r removing ipsw/extracted

**Comment by Aditya20110** [comment]
Means edwin is missing something required

**Comment by Tech4HelpYT** [comment]
> Means edwin is missing something required

Yep, but on his I can downgrade and boot, but yours I cannot even downgrade (Ubuntu Linux 22.10).

**Comment by Tech4HelpYT** [comment]
Whenever I try downgrading, before second dfu mode, it says cp: -r removing ipsw/extracted. (GUI on 22.10)

**Comment by Tech4HelpYT** [comment]
f

> Means edwin is missing something required

I'll try taurine and get back to you later today (like 3PM EST)

**Comment by Aditya20110** [comment]
Bro listen

**Comment by Aditya20110** [comment]
I did tried it and it worked for me

**Comment by Aditya20110** [comment]
Did u used sudo? Or did it asked for your system password after executing?

**Comment by Aditya20110** [comment]
Provide some screenshots pls

**Comment by Aditya20110** [comment]
![image](https://user-images.githubusercontent.com/101180337/234554720-22bf3154-c6df-4230-b79b-0cba21aad921.jpeg)

It works properly and tested

**Comment by Aditya20110** [comment]
> 

bro this is not issue of gui.you know what gui means.it do the work of automatically entering commands by clicking.

**Comment by Tech4HelpYT** [comment]
> > 
> 
> bro this is not issue of gui.you know what gui means.it do the work of automatically entering commands by clicking.

I didn't run sudo, I'll try with sudo.

**Comment by Tech4HelpYT** [comment]
sudo also outputted the same result, even with the new update that has dualr1n-loader.ipa

**Comment by Tech4HelpYT** [comment]
Device: iPhone 7 Plus

iOS: 15.1.1 trying to downgrade to 14.8, 14.6, 14.4, or 14.3

(I tried all those versions, and still same problem)

**Comment by Aditya20110** [comment]
Send me logs without that I can’t confirm whats the problem either it is your system.because there are no bugs i have tested it and I’m updating it regularly

**Comment by Tech4HelpYT** [comment]
Please help.

**Comment by Tech4HelpYT** [comment]
System: Lubuntu 22.10

**Comment by Aditya20110** [comment]
Ok,can u give a try on ubuntu? Means some dependencies are missing

**Comment by Tech4HelpYT** [comment]
Didn't work, I tried on ubuntu (I also ran install.sh, on both ubuntu and lubuntu) and now it is stuck on [*] Waiting for ramdisk to finish booting, and on the iPhone it gets stuck on:

SSHRD_Script by Nathan (verygenericname)
Running server

**Comment by Tech4HelpYT** [comment]
I'm going to try with normal downr1n, since I see it got updated, will respond if it works!
