### ISSUE TITLE
Fix the install.sh script to be up to date

### ISSUE THREAD

**Issue by Tech4HelpYT** [Aditya20110/downr1n-gui#14]
Can you please update install.sh script in this repo to the one from edwin's repo (the new one with jailbreak fixes)?

**Comment by Aditya20110** [comment]
I will check it

**Comment by Aditya20110** [comment]
Yeah, edwin fixed the issue. I will surely update the sh soon

**Comment by Aditya20110** [comment]
im closing this issue now.the gui is working fine without any issues.thank you
