### ISSUE TITLE
"only Ubuntu is supported"

### ISSUE THREAD

**Issue by DarwinUang** [Aditya20110/downr1n-gui#15]
..even though I can literally *run this thing on Windows*

I mean, did you say that only Ubuntu is supported because you were lazy, or did you do it because you didn't have the technical expertise to install another distro?

![image](https://user-images.githubusercontent.com/61612754/235281528-34c74236-bb6c-4314-a88c-fd906e8b8107.png)

**Comment by Aditya20110** [comment]
Are u stupid? This can be executed on windows also ,but there are very complicated drivers for usb. Idk why u ask stupid questions

**Comment by Aditya20110** [comment]
Mean?

**Comment by Aditya20110** [comment]
This will just execute in windows but will never work

**Comment by Aditya20110** [comment]
Whatever.this will work on linux (every linux distros) and for mac os the branch is already present.

**Comment by Tech4HelpYT** [comment]
> > Whatever.this will work on linux (every linux distros) and for mac os the branch is already present.
> 
> you didn't even test that, and APT does not exist on every Linux distro, so no, you are mistaken and it does not work on every Linux distro.
> 
> [install.sh](https://github.com/Aditya20110/downr1n-gui/blob/main/install.sh)

It doesn't work in WSL 2, stop and go f*** off and make your own gui if you disagree with this.

**Comment by Aditya20110** [comment]
It is not feasible to include all package managers in one script as each package manager has its own unique commands and syntax.but still i added most linux distro support.i also added yum package manager.but i will try to add

**Comment by Aditya20110** [comment]
And why are you so dumb,that you are going into jailbreaking stuff and you even don't know how to install dependencies,better you give up

**Comment by Aditya20110** [comment]
I’m working on it.just shut up
