### ISSUE TITLE
everything wrong with your script

### ISSUE THREAD

**Issue by DarwinUang** [Aditya20110/downr1n-gui#16]
```
#!/bin/bash/
if [ "$EUID" -ne 0 ]
  then
  echo "Please run with SUDO (as root)"
  exit
fi
if [[ -f "/etc/lsb-release" || -f "/etc/debian_version" ]]
    then
        echo "Linux Ubuntu detected and is supported"
    else
        echo "This Linux Distro is not supported, exiting..."
        exit
    fi
echo "Written by Burhan Rana - YouTube: www.youtube.com/burhanrana / Twitter: https://twitter.com/burhangee"
echo "This script automatically installs all required dependencies for Palera1n Jailbreak, Dualra1n dualbooter, Downr1n Downgrader and such software"
sudo add-apt-repository universe && sudo apt-get update && sudo apt install libimobiledevice-utils libusbmuxd-tools git curl python3-pip unzip clang -y && python3 -m pip install pyimg4 && pip install requests remotezip pyimg4 pyqt5 applescript && sudo apt-get install python3-tk && sudo apt-get install python3-pil python3-pil.imagetk && pip install pyqt5 && sudo wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb && sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb && sudo rm libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
echo "All Done!"
```

- assumes `/bin/bash` exists - even if it does, the path `/bin/bash` is not standardized ([NixOS](https://nixos.org) being a great example of this). instead, you are encouraged to use [`/usr/bin/env`](https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability).
  - of course, this creates another issue, which is that `/usr/bin/env` is not standardized either. there is no fix for this, so just be aware of that.
- assumes `sudo` exists - contrary to popular belief, `sudo` is not standardized and is not even installed by default on the more "power user oriented" distros (such as [Arch](https://archlinux.org) and [Gentoo](https://wiki.gentoo.org/wiki/Main_Page) (with Gentoo users preferring [OpenDoas](https://wiki.gentoo.org/wiki/Doas) because it is more lightweight)).
  - you do not even need to check if `$EUID` is equal to `0` because the script already calls `sudo` for privilege escalation
    - thus, either stop using `sudo`, or remove the `$EUID` check
- uses `sudo` to `wget`
  - what the hell are you doing
- checks if the distro is Ubuntu
  - like what the fuck, there are better ways to implement this check, and it looks like you have a lot of spare time
    - for example, `uname -a | grep Ubuntu`
    - for example, `lsb_release -a | grep Ubuntu`
- "Linux Ubuntu"
  - it's "Ubuntu Linux", or sometimes just "Ubuntu"
- "Distro"
  - why are you capitalizing "distro"

although I guess I should have expected as much considering this script was made by a tech illiterate YouTuber
> `echo "Written by Burhan Rana - YouTube: www.youtube.com/burhanrana / Twitter: https://twitter.com/burhangee"`

**Comment by Aditya20110** [comment]
Bro,why the hell you are chasing me.i have not made it.burhan has made it,and dont say him illiterate bro.

**Comment by Aditya20110** [comment]
Follow github guidelines and be polite,i will change the script accordingly

**Comment by Aditya20110** [comment]
i fixed it sorry for inconvenience
