### ISSUE TITLE
at this point you might as well stop trying

### ISSUE THREAD

**Issue by DarwinUang** [Aditya20110/downr1n-gui#17]
`#!/bin/bash`
why

`sudo rm libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb`
why

**Comment by Aditya20110** [comment]
are u stupid or you have skill issue? This is bash script as described.and libssl is used to fix libssl issue

**Comment by Aditya20110** [comment]
Ooh now I understood what u wanted to say

**Comment by Aditya20110** [comment]
Im fixing it now,also libssl url is broken xd

**Comment by Aditya20110** [comment]
Will do it now,sorry for inconvenience

**Comment by Aditya20110** [comment]
script is fixed.thank you for using gui
