### ISSUE TITLE
Error xcb

### ISSUE THREAD

**Issue by iEnderman55** [Aditya20110/downr1n-gui#4]
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

**Comment by Aditya20110** [comment]
Which operating system u are using? ,mac or linux

**Comment by iEnderman55** [comment]
Linux, Ubuntu

**Comment by Aditya20110** [comment]
Bro it means u didn’t installed pyqt5 correctly

**Comment by Aditya20110** [comment]
Type 

pip install pyqt5 

and if it doesn’t works type-


Sudo apt-get install libxcb-xinerama0

**Comment by iEnderman55** [comment]
i have used this command: pip install PyQt5 (also with sudo) but it doesn't work

**Comment by Aditya20110** [comment]
oh ok

**Comment by Aditya20110** [comment]
hmm.. It seems like there's an issue with the XCB platform plugin. You may need to install some dependencies or set the correct environment variables. run the command -

export QT_QPA_PLATFORM=xcb

and please run this command also-

sudo apt-get install libxcb-xinerama0

this will surely fix this issue.

**Comment by Aditya20110** [comment]
can u send me some screenshots? so i will understand better,and does the program runs even?

**Comment by iEnderman55** [comment]
OK, but I don't need it anymore your help, now it works magically. Thanks the same

**Comment by Aditya20110** [comment]
well, good luck for your downgrade!
