### ISSUE TITLE
Can't switch my device in recovery mode

### ISSUE THREAD

**Issue by iEnderman55** [Aditya20110/downr1n-gui#5]
*] Waiting for devices
[*] Detected normal mode device
/home/francy/Scrivania/downr1n-gui/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/home/francy/Scrivania/downr1n-gui/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Hello,  on 14.3!
[*] Switching device into recovery mode...
/home/francy/Scrivania/downr1n-gui/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/home/francy/Scrivania/downr1n-gui/binaries/Linux/ideviceenterrecovery: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by Aditya20110** [comment]
hhh bro,did u run install.sh

**Comment by Aditya20110** [comment]
run this command-

sudo apt-get install libssl-dev

after that run-

sudo ldconfig

**Comment by Aditya20110** [comment]
bro, use git pull,i have fixed the error.sorry for inconvenience.

**Comment by Aditya20110** [comment]
and bro please make sure that you run install.sh

**Comment by iEnderman55** [comment]
I have this: error: local changes to the following files would be overwritten with the merge:
binaries/Linux/gasters
Commit or hide your changes before merging.
I interrupt the operation

**Comment by Aditya20110** [comment]
Bro reclone it in different directory

**Comment by iEnderman55** [comment]
I have replace binaries and runned sudo bash install.sh but nothing, doesn't work

**Comment by Aditya20110** [comment]
Bro please send screenshots

**Comment by Uckermark** [comment]
Use normal downr1n :trollface: /jk

Run

> wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb

and

>sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb

Then reclone repo and try again

**Comment by Aditya20110** [comment]
Yeah

**Comment by Aditya20110** [comment]
@Uckermark checkout semira1n also

**Comment by iEnderman55** [comment]
Now I have this: *] Device entered DFU!
[*] Continuing...
extracting ipsw, hang on please ...
Archive:  ipsw/iPad_64bit_TouchID_ASTC_14.3_18C66_Restore.ipsw
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  ipsw/iPad_64bit_TouchID_ASTC_14.3_18C66_Restore.ipsw may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of ipsw/iPad_64bit_TouchID_ASTC_14.3_18C66_Restore.ipsw or
        ipsw/iPad_64bit_TouchID_ASTC_14.3_18C66_Restore.ipsw.zip, and cannot find ipsw/iPad_64bit_TouchID_ASTC_14.3_18C66_Restore.ipsw.ZIP, period.

**Comment by Aditya20110** [comment]
Bro it works for others but idk why ur one is lacking somewhere

**Comment by Uckermark** [comment]
Your ipsw might be corrupted. Can you run 
`ls -lah ipsw/`

Why don't you dualboot? Should be possible on your device.

**Comment by iEnderman55** [comment]
I have this: totale 3,9G
drwxrwxr-x  2 francy francy 4,0K apr 21 15:29 .
drwxrwxr-x 10 francy francy 4,0K apr 21 16:42 ..
-rwxrwxr-x  1 francy francy 3,9G apr  6 15:35 iPad_64bit_TouchID_ASTC_14.3_18C66_Restore.ipsw
-rw-rw-r--  1 francy francy    1 apr 21 14:46 .ipsw

**Comment by iEnderman55** [comment]
I'm using 57,8 GB in 128GB of space

**Comment by Aditya20110** [comment]
Bro.idk why you are facing this issue. It is a request to send the pictures of the issue

**Comment by iEnderman55** [comment]
141 GB of free space

**Comment by iEnderman55** [comment]
> Bro.idk why you are facing this issue. It is a request to send the pictures of the issue

![Schermata del 2023-04-21 17-02-54](https://user-images.githubusercontent.com/110713827/233669859-e5e23e15-e524-440a-8cb8-95818ae0f7f4.png)
![Schermata del 2023-04-21 17-03-02](https://user-images.githubusercontent.com/110713827/233669871-ee2e24e5-8375-41b0-9eda-2df10525e79e.png)
![Schermata del 2023-04-21 17-02-38](https://user-images.githubusercontent.com/110713827/233669879-6c1f30cf-25c7-4044-929a-45f2e9c50277.png)

**Comment by emad2333** [comment]
But semira1n was I development and advised not to use

**Comment by Uckermark** [comment]
> But semira1n was I development and advised not to use

Thats the thruth. What is your question?

**Comment by Aditya20110** [comment]
I am closing this issue because you are not clear about the issue our recommendation is-

Download ipsw from ipsw.me 

Reinstall all dependencies 

Use git pull.

Thanks
