### ISSUE TITLE
stuck on rsep nonce (20 bytes): 1330612a3c1d2178c973f8a14044aaabe2def871

### ISSUE THREAD

**Issue by Rickyayaya** [Aditya20110/downr1n-gui#9]
title

**Comment by Aditya20110** [comment]
You are trying it on ios 16 right? Because on ios 16 ssh ramdisk is not properly functional.

**Comment by Aditya20110** [comment]
So no support for ios 16.

**Comment by Rickyayaya** [comment]
no, im trying to downgrade from 14.4 to 14.3

**Comment by Rickyayaya** [comment]
yes.
